version: "3.8"

networks:
  node-red-net:
    driver: bridge

services:
  node-red:
    build: .
    container_name: fireplace-node-red
    environment:
      - TZ=Europe/Stockholm
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data/node-red:/data
  influxdb:
    image: influxdb:1.8
    container_name: fireplace-influxdb
    ports:
        - 8086:8086
    environment:
        INFLUXDB_HTTP_AUTH_ENABLED: "true"
        INFLUXDB_DB: "${DB}"
        INFLUXDB_ADMIN_USER: "${DB_USER}"
        INFLUXDB_ADMIN_PASSWORD: "${DB_PASS}"
    networks: 
        - node-red-net
    volumes:
        - ./data/influxdb:/var/lib/influxdb